### ISSUE TITLE
blob-dir is not enabled by default

### ISSUE THREAD

**Issue by FarooqAlaulddin** [zopefoundation/zope.mkzeoinstance#15]
### What I did: 
- I installed & configured plone 6 installation following the official documentation at [Plone 6: The Install](https://6.docs.plone.org/install/install-from-packages.html#install-plone-from-its-packages)
  - this gave me 1 instance with direct db.
- I wanted to scale up with multiple instances using ZEO server, so I followed [Ex: Plone Multi Clients using ZEO ](https://community.plone.org/t/example-of-two-clients-and-a-zeo-server-with-a-pip-installation-of-plone-6/15518#example-how-to-create-a-zeo-cluster-with-plone-6-and-pip-1)

### What I expect to happen:
- &#10003; Multi clients/instances sharing ZEO database on localhost:8100.
- &#10003; Ability to connect to ZEO database from multiple clients.
- &#10003; Ability to add/edit/remove from any client.
- **&#10005; Ability to upload files from any client.**
### What actually happened:
- Was not able to upload files and getting this error: https://github.com/plone/Products.CMFPlone/issues/3345#issue-1037650436
- Clients are able to connect to ZEO server and add/edit data **but not blob**
### How it was solved:
- Using `cookiecutter-zope-instance`, directing the blob location for the instance to the ZEO blob file:
  - Ex: `db_blobs_location: /path/to/zeo/var/blobs`: 
  - This will generate the following zope.config
    ![image](https://user-images.githubusercontent.com/37892823/230026005-081dc366-317d-43ca-8eab-efed10d888a7.png)
- Now, to create a ZEO server, I used `mkzeoinstance zeo localhost:8100`
  - This will generate /zeo/etc/zeo.conf - **Edit fix on line 17**
     ![image](https://user-images.githubusercontent.com/37892823/230028208-f90826d0-e413-4800-9d84-15f267df6c71.png)
  - **Doing so fix the file upload problem.**

### What version of Python and Zope/Addons I am using: Python 3.9 - leatest.

**Comment by icemac** [comment]
Adding a configuration option to pass in the path to the blob directory would be appreciated. A pull request is welcome.
