### ISSUE TITLE
Travis-CI thinks "This is not an active repository"

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.mkzeoinstance#4]
See https://travis-ci.org/zopefoundation/zope.mkzeoinstance

**Comment by jamadden** [comment]
The integration was set up, so I don't know why it was showing that. I had to delete it and re-add it, but it shows up as active now, for me at least.

**Comment by icemac** [comment]
@jamadden Thank you, works here, too.

**Comment by mgedmin** [comment]
> The integration was set up, so I don't know why it was showing that

Maybe the setup was incomplete in some way?  There's precedent: https://github.com/zopefoundation/zope.githubsupport/issues/1
