### ISSUE TITLE
Release 4.0

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.mkzeoinstance#5]
After merging #3 It would be nice to have a new release.

@tseaver You are the only one who is allowed to release this package to PyPI.
Would you like to make a release or share the right on PyPI? (My handle there  is "icemac".)

**Comment by tseaver** [comment]
@icemac I added you.

**Comment by icemac** [comment]
@tseaver Thank you.
@cclauss I released 4.0 to [PyPI](https://pypi.org/project/zope.mkzeoinstance/4.0/)
